services:
  - type: web
    name: roadmap-generator
    env: node
    buildCommand: bun install && bun run build
    startCommand: bun start
    envVars:
      - key: NODE_VERSION
        value: 20.15.1
      - key: GROQ_API_KEY2
        sync: false